[project]
name = "yxi-chat-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "python-docx>=1.1.0",
    "uvicorn>=0.30.0",
]
